<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product</name>
   <tag></tag>
   <elementGuidId>7517f42b-c763-4dd0-bf57-0939ea12a290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/section/article/div[3]/div/div/div[2]/ul/li[1]/p[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/section/article/div[3]/div/div/div[2]/ul/li[1]/p[1]/a</value>
      <webElementGuid>896c39d2-712e-40fe-8982-f86d12c4bdb9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
