<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup</name>
   <tag></tag>
   <elementGuidId>5e31edd3-68fc-4b69-85cd-59491da7b771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//login-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//login-modal</value>
      <webElementGuid>3327cc5d-4977-4e4f-9776-2c4fd80da680</webElementGuid>
   </webElementProperties>
</WebElementEntity>
