<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>username-field</name>
   <tag></tag>
   <elementGuidId>18cfcba6-afb7-49e9-87b4-d0559ecef8b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>5b880212-85b0-4227-8ca3-95069e07a20a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
